version: "3.8"

services:
  hello-node:
    image: opklnm102/hello-node:c856ec4a1a5ee980d8b3c4fb4c348282fba56236
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.19.9-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
